### ISSUE TITLE
Backend-Module "New Client" fails on checking cli-permissions

### ISSUE THREAD

**Issue by albig** [kitodo/kitodo-presentation#210]
The backend module "new client" claims to check the group permissions for _cli_dlf. Actually the test is positive even when the permission is not set.

The test has to be verified.

**Comment by sebastian-meyer** [comment]
Since TYPO3 8.0 there is no need for a CLI user anymore. TYPO3 automatically creates an admin user called "\_cli\_" when the CLI dispatcher is called the first time and this user is then used for every CLI request. So this problem only exists in TYPO3 <= 7.6, which isn't supported anymore.

I have therefore removed the creation of "_cli_dlf" user and usergroup as well as all the checks.
