### ISSUE TITLE
Link authors with GND reference

### ISSUE THREAD

**Issue by albig** [kitodo/kitodo-presentation#214]
Introduced by this feature:

https://github.com/kitodo/kitodo-presentation/blob/f0e0d13f6f86d12fc8f74a942bccac0571b0036e/dlf/common/class.tx_dlf_mods.php#L101

The author field contains a full href link. In the list module, this link is rendered through htmlspecialchar(). Same occures in SOLR index. This should be refactored.

**Comment by sebastian-meyer** [comment]
I suggest leaving the htmlspecialchar() in for security reasons. Otherwise someone could send a forged METS file via `tx_dlf[id]` and any code (i.e. javascript) in the MODS fields would be executed.

Instead we should handle the GND reference as a separate metadata field. The a-tag can be generated by TS via metadata configuration. But we need to find a way to assign a GND reference to a certain author field.

**Comment by sebastian-meyer** [comment]
Fixed by #409
