### ISSUE TITLE
Add support for TYPO3 v8 LTS

### ISSUE THREAD

**Issue by stweil** [kitodo/kitodo-presentation#264]
Kitodo.Presentation currently supports TYPO3 v7 LTS.

According to https://typo3.org/download/, security-related and important bugfixes will be provided for that version until November 2018.

Therefore we need an upgrade path to newer versions of TYPO3. Because of API changes those versions currently do not work with Kitodo.Presentation.

I added this issue to collect all information needed to implement support for newer TYPO3 versions and to exchange plans and activities between interested parties and institutions.

**Comment by stweil** [comment]
An upgrade from TYPO3 v7 LTS to TYPO3 v9 only works after an upgrade to TYPO3 v8 LTS, so both v8 and v9 must be supported by a future version of Kitodo.Presentation.

**Comment by stweil** [comment]
Known problems:

    # Error occurring when trying to configure Kitodo.Presentation in the TYPO3 backend.
    Call to undefined method TYPO3\CMS\Core\Messaging\FlashMessage::render() 
    Error thrown in file /var/www/html/typo3conf/ext/dlf/hooks/class.tx_dlf_em.php in line 655.

The TYPO3 install tool reports this for the dlf (= Kitodo.Presentation) extension:

    TCA migrations need to be applied

and

    Extensions change TCA in ext_tables.php
    Check for ExtensionManagementUtility and $GLOBALS["TCA"].

**Comment by albig** [comment]
The TCA migrations is almost done. The remaining part should be moved to `Configuration/TCA/Overrides/tt_content.php`. 

The FlashMessage doesn't have a method render() anymore as of TYPO3 8.

Also known: The backend modules won't work anymore.

<pre>
TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addModulePath() - since TYPO3 CMS 7, will be removed in TYPO3 CMS 8, use routeTarget or dispatched modules instead.

Registered "txdlfmodules_txdlfnewclient" as a script-based module. Script-based modules are deprecated since TYPO3 CMS 7. Support will be removed with TYPO3 CMS 8, use the "routeTarget" option or dispatched modules instead.
Registered "txdlfmodules_txdlfindexing" as a script-based module. Script-based modules are deprecated since TYPO3 CMS 7. Support will be removed with TYPO3 CMS 8, use the "routeTarget" option or dispatched modules instead.
Registered "txdlfmodules" as a script-based module. Script-based modules are deprecated since TYPO3 CMS 7. Support will be removed with TYPO3 CMS 8, use the "routeTarget" option or dispatched modules instead.

</pre>
Maybe we should open multiple issues for each migration task and tag it with e.g. [TYPO3-8].

**Comment by sebastian-meyer** [comment]
I started a branch to drop support for TYPO3 6.2 and add support for TYPO3 8.7: https://github.com/kitodo/kitodo-presentation/tree/typo3-8.7

There is still a lot to do:
- [x] remove compatibility layer for TYPO3 6.2
- [x] add namespaces to all common classes
- [x] rename common classes and class files according to conventions
- [x] switch to psr-4 compatible autoloading in composer.json
- [x] add static database data for tx_dlf_formats table (MODS, TEIHDR, ALTO)
- [x] move plugin classes to Classes/Plugins/
- [x] move module classes to Classes/Modules/
- [x] move flexforms to Configuration/Flexforms/
- [x] move templates to Resources/Private/Templates/
- [x] move localisation files to Resources/Private/Language/
- [x] update tx_emconf.php and composer.json with dependencies
- [x] ensure class loading of PHP and PECL classes like DOMDocument, SimpleXMLElement and DOMXPath
- [x] remove deprecated functions or provide backports
- [x] rebuild backend modules for TYPO3 7.6+
- [ ] convert old locallang.xml files to XLIF

**Comment by sebastian-meyer** [comment]
Here are some more things to do:
- [ ] Create SVG icon for backend module
- [ ] Fix usage of broken default language keys in flexforms
- [ ] Migrate plugins to Extbase and Fluid
- [ ] Re-Implement backend module with proper ActionControllers

**Comment by sebastian-meyer** [comment]
We now have general compatibility with TYPO3 8.7.

To reach compatibility with TYPO3 9+ we have to go even further and get rid of the old `css_styled_content` based plugin rendering.

I'll close this issue and we should open another one for compatibility with TYPO3 9+.

**Comment by stweil** [comment]
Thank you, Sebastian. I see that you were very busy with lots of new commits the last days – just in time for Bibtag19.

**Comment by lutzhelm** [comment]
A question: Is it intentional that the Indexing module is no longer present? Should documents be saved and indexed solely via the `CommandLineIndexer`?

**Comment by sebastian-meyer** [comment]
Yes. indexing via the backend module was very slow and error prone (because of the JS-based page reloading). The CommandLineIndexer is more stable, faster and provides the same features (i. e. re-indexing collections).
