### ISSUE TITLE
Unable to create working page with Collection plugin in Typo3 8.7

### ISSUE THREAD

**Issue by jmechnich** [kitodo/kitodo-presentation#343]
### Steps to reproduce
- Follow the Kitodo.Production.3 tutorial [here](https://github.com/kitodo/kitodo-tutorials/tree/master/kitodo3)
  - Add one or more documents in order to create at least one collection.
  - Add a couple of Typo3 pages following the tutorial pages 12-14.
  - Try adding a page containing the Collection plugin.

### Expected behaviour
After pointing the Startingpoint to the correct data folder and setting the Target Page to the page containing the List View plugin, available collections should show up for selection.

### Actual behaviour
The correct Solr Core is selected, but no available collections are shown. After pressing the save button for a second time, the available collections are displayed but the selected Solr Core vanishes and the drop-down list is empty. After this it is not possible to save again as no Core can be manually selected.

The following error shows up in system and dev log after the first save:
> Core: Error handler (BE): PHP Warning: Invalid argument supplied for foreach() in /var/www/typo3/CmsBaseDistribution/public/typo3conf/ext/dlf/Classes/Hooks/FormEngine.php line 57

### System configuration
- Debian 9 stretch
- MySQL Server 5.7.25-1debian9
- Typo3 8.7.25 (installed with composer)
- Kitodo.Presentation 3.0.0 (installed with composer)
- Solr 7.7.1 (installed from tgz)

**Comment by ghost** [comment]
Hi Jörg,
first of all: dlf presentation 3 is beta and it has still a lot of bugs. It is not yet suitable for a productive use.

We worked around this issue by patching FormEngine.php on line 195 (function itemsProcFunc_solrList) from
`$page = $params['row']['pages'];`
to
`$page = $params['row']['pages'][0]['uid'];`
to get the following DB select Query for the solr core label & uid working. 

I would leave this issue open, so the maintainers can care about it, if they have the time for it.
Keep going the good work, dont give up, there is a lot more still to come.

**Comment by BFallert** [comment]
This workaround works! I can now save a page with a Collection plugin.

**Comment by sebastian-meyer** [comment]
I provided a pull request which tries to fix this problem for all `itemsProcFunc_*`. Could you please verify that fix #344 works as expected?

**Comment by ghost** [comment]
My Test failed. Problem still persists.

Setup: 
- Ubuntu 18.04.2 LTS
- TYPO3 8.7.26 (composer mode)
- Solr 7.7.1
- MySQL 5.7.26
- Kitodo Presentation (dev-fix-343 f49de4b)

Indexing to Solr & Typo3 DB succeeded, 2 solr cores active, 2 collections active, 2 documents active, but no solr-core is selectable in Flexform for Collection Plugin Config and no Collections are shown in Collection Available Items. Page cannot be saved due to "Require" Restrictions.

This Warning is in TYPO3 Log:
`Core: Error handler (BE): PHP Warning: Invalid argument supplied for foreach() in /var/www/kitpres8-test/public/typo3conf/ext/dlf/Classes/Hooks/FormEngine.php line 120`

Debugger indicates following call (itemsProcFunc_solrList) returns NULL:
`$this->itemsProcFunc_generateList(
             $params,
             'label,uid',
             'tx_dlf_solrcores',
             'label',
             'OR pid=0',
             FALSE
         );`

In my testcase FormEngine.php line 117 `$pages = $params['row']['pages']` is neither array nor object, but string: 1 char: '3' (uid of data folder)

**Comment by jmechnich** [comment]
We introduced a helper function to check if $pages is an array or a string to fix this issue, see https://github.com/jmechnich/kitodo-presentation/commit/61d6617f9b001ae137e64a53d5e9ad3a1cad1f00

Maybe this can be combined with Sebastians patch ? I am a bit confused though why the type of $pages is not always an array in the first place.

**Comment by sebastian-meyer** [comment]
Thank you for your contribution! I updated #344 accordingly. Could you please test again?

**Comment by BFallert** [comment]
I tested it again, now its possible to create working page with Collection plugin! 

So the problem is fixed now! Thanks for that!

**Comment by ghost** [comment]
Yes. Tested dcb5120 and saving a Collection Plugin Page works now.
