### ISSUE TITLE
Plugins "Feeds" and "OaiPmh" break TYPO3 output handling

### ISSUE THREAD

**Issue by frank-ulrich-weber** [kitodo/kitodo-presentation#471]
## Description

In my configuration no or an invalid output is created by the use of ob_end_clean() instead of ob_clean() within the main methods of class OaiPmh (L396) and Feeds (L167). How can I solve this error without replacing ob_end_clean() by ob_clean()?

## Expected Behavior

Valid output

## Screenshots and Examples

![grafik](https://user-images.githubusercontent.com/4659074/74032673-d71a7e00-49b4-11ea-8d5b-ef0a38744b4a.png)

## Environment

 - OS version: Windows 10
 - RDBMS version: MySQL 5.7.20
 - Apache Solr version: 7.4
 - TYPO3 version: [e.g. 8.7.29]
 - PHP version: 8.7.30

**Comment by sebastian-meyer** [comment]
If TYPO3 is configured to use content compression, it automatically sets the corresponding headers. But the way the `OaiPmh` and `Feeds` plugins "echo" their content overrides the TYPO3 bootstrapping and output handling.
Instead of just replacing `ob_end_clean()` with `ob_clean()` we should refactor the output handling by using the proper `Response` object and setting headers with `\TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController`.
