### ISSUE TITLE
Composer dependencies of solarium client

### ISSUE THREAD

**Issue by ByteParty** [kitodo/kitodo-presentation#578]
The solarium updates creates an incompatibility to other extensions e.g. ext:solr. For systems using both extensions this is problematic. So no composer updates/installations will work anymore.
https://github.com/TYPO3-Solr/ext-solr/blob/master/composer.json#L33
https://github.com/kitodo/kitodo-presentation/blob/master/composer.json#L38

**Comment by sebastian-meyer** [comment]
Solarium 4.x hasn't received updates since more than 2 years, so I don't consider it a bug if we don't support this version anymore. This is more an issue of `ext:solr` not supporting current versions of Solarium than an issue of `ext:dlf` not supporting very old versions.

Furthermore, the developers of `ext:solr` are already working on supporting current versions of Solarium: https://github.com/TYPO3-Solr/ext-solr/issues/2636

**Comment by albig** [comment]
Maybe "Bug" is the wrong tag. But we should find a working solution für TYPO3 9.5 (at least). The solr extension won't make a release for TYPO3 9.5 and Solarium 6 as far as I've read.

Why did we switch to Solarium 5.2.0 in Kitodo.Presentation? And can't we provide both as `EXT:typo3-find`? The difference is this path-handling?

**Comment by sebastian-meyer** [comment]
We switched to a current Solarium version for a couple of reasons:

1. Generally speaking we are in the process of updating all outdated dependencies and components (Solarium, OpenLayers, jQuery, etc.).
2. We want to support the Solr extension [solr_ocrhighlighting](https://github.com/dbmdz/solr-ocrhighlighting) which requires Apache Solr >= 7.5.
3. Solarium 5.x is the newest version still compatible with Solr >= 7.5.
4. Solarium 5.x is the newest version not requiring an EventDispatcher (which isn't included in TYPO3 prior to version 10.x).

So the plan is to have another release of Kitodo.Presentation (3.2) which still supports TYPO3 8.x and 9.x, but comes with updated dependencies and components. This release is required for the Zeitungsportal as well.

After that we will have the next major release (4.0) which drops support for TYPO3 8.x and adds support for TYPO3 10.x. We are still undecided whether this will depend on Solarium 6.x (and therefore requiring the Symfony EventDispatcher even when using TYPO3 9.x) or keep Solarium 5.x.

Has anyone already tried using `ext:solr` with Solarium 5.2? You would have to remove the `/solr` part of the Solr path from configuration, because Solarium 5.x adds it automatically, but other than that, there are no breaking changes I am aware of (see https://github.com/solariumphp/solarium/releases/tag/5.0.0).

**Comment by albig** [comment]
I think we still must support Solarium 4.2.0 in the upcoming Kitodo.Presentation 3.2 release, too. None of the arguments above justifies such a breaking change in this minor release. We already support and use Solr 7.5 for years now.

If it's only the path issue, we should reach something like `~4.2 || ~5.1` for the Solarium constraints easily like `ext:typo3-find` claims it already.

**Comment by sebastian-meyer** [comment]
OK, I'll try to find a solution to support both major versions at the same time...

**Comment by sebastian-meyer** [comment]
I provided a pull request which should support Solarium 4.x.

Please do extensive testing since I didn't test it myself. 😏
