### ISSUE TITLE
Regression error if implementing AbstractPlugin with different extension key.

### ISSUE THREAD

**Issue by albig** [kitodo/kitodo-presentation#613]
With #610 it was introduced to use the `ExtensionConfiguration::class ` to access the extension configuration. This will fail at the following line with a plugin implementing the AbstractPlugin class which use a different `extKey`. 

This is done with some [DFG-Viewer plugins](https://github.com/slub/dfg-viewer/tree/master/Classes/Plugins). The DFG-Viewer has no extension configuration and the result is an exception:

```
(1/1) #1509654728 TYPO3\CMS\Core\Configuration\Exception\ExtensionConfigurationExtensionNotConfiguredException
No extension configuration for extension dfgviewer found. Either this extension has no extension configuration or the configuration is not up to date. Execute the install tool to update configuration.
```

The solution would be to set the extension key 'dlf' explicitly on the following line:

https://github.com/kitodo/kitodo-presentation/blob/497d15ee562fbcf1124042c2dafb87a7468aea8f/Classes/Common/AbstractPlugin.php#L116

**Comment by sebastian-meyer** [comment]
The `AbstractPlugin` intentionally uses `$this->extKey` instead of a hard-coded `dlf`. This was done to allow plugins of other extensions which provide additional functionality for Kitodo.Presentation or re-use the framework to also derive their plugins from `AbstractPlugin` but use their own configuration. So this is a feature, not a bug.

The only difference now is, that there is an exception thrown if no extension configuration exists. Before #610 this was just ignored.

So, instead of always using `dlf` as extension key I suggest checking for the existence of an extension configuration before trying to fetch it (but keep using `$this->extKey`). Otherwise this might break other extensions, which are currently using Kitodo as a framework.

**Comment by albig** [comment]
I fully agree, after thinking again about this. From TYPO3 10.4 on, there is a function `ExtensionConfiguration::hasConfiguration()` which does the same we do some lines later anyway:

```
protected function ‪hasConfiguration(string $extension): bool
     {
         return isset(‪$GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS'][$extension]) && is_array(‪$GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS'][$extension]);
     }
```

I'll check this and will provide a pull request. For the `AbstractModule` this is - in theory - the same.
