### ISSUE TITLE
Indexing of documents creates lots of bad new entries in list of libraries

### ISSUE THREAD

**Issue by stweil** [kitodo/kitodo-presentation#81]
While indexing some parts of our collection, we noticed a strange phenomenon: we got lots of entries in the table of libraries ("Mandanten" in German TYPO3, table tx_dlf_libraries in MySQL).

The relevant code in function tx_dlf_document.save looks for the correct library (columns pid and index_name in table tx_dlf_libraries) and inserts a new library if it did not find one.

Usually it expects an empty index_name (Are other value supported, too? Is $metadata['owner'][0] ever set?). If a new library is inserted, it gets the correct pid, but an index_name which is null (!= empty string). When the same document is indexed again, that null index_name won't match the DB search criteria, so one more library is inserted. This can be repeated ad infinitum.

**Comment by sebastian-meyer** [comment]
If $metadata['owner'] is set depends on your metadata configuration and the MODS encoding. Usually the owner information is expected in ./mods:name[./mods:role/mods:roleTerm="own"]/mods:displayForm (see dlf/modules/newclient/metadata.inc.php), but you can of course change that xpath in the backend.

But you are right, tx_dlf_document.save should support an empty owner, too. I am not sure, why the index_name is set to NULL, especially since the database field is defined as "index_name tinytext NOT NULL" (see dlf/ext_tables.sql).
