### ISSUE TITLE
[FUND] Support for TYPO3 12 LTS

### ISSUE THREAD

**Issue by sebastian-meyer** [kitodo/kitodo-presentation#900]
## Description

The upcoming Kitodo.Presentation 5.0 release will support TYPO3 10 ELTS and 11 LTS. The next [TYPO3 LTS version](https://typo3.org/cms/roadmap) is already released:

* [TYPO3 12 LTS](https://get.typo3.org/)

The next major release 6.x should support TYPO3 11 LTS and 12 LTS.

## Expected benefits of this development
* Developer / Maintainer
   * This is mandatory. We cannot ignore the development of the upstream TYPO3 CMS. It pushes the development and makes sure Kitodo.Presentation is an up-to-date tool.
* Administrators
   * Run supported TYPO3-version is obligatory.

## Estimated Costs and Complexity

I assume this should be a **medium cost** project for TYPO3 12, since there are just a few breaking changes to be expected. But the minimum PHP version will increase from 7.4 to 8.1, which requires some changes. Since TYPO3 11 LTS is supported until 2024-10-31, this is IMHO a must-do for the development fund 2024.

**Comment by sebastian-meyer** [comment]
Votes: 7

**Comment by stweil** [comment]
I think that it would be good if this and other similar tasks would also update https://github.com/kitodo/kitodo-demo (and the related online demo if that still exists). In addition the documentation should be updated and also include instructions how to upgrade from previous versions of the software. I suggest to add that as requirements here.

**Comment by sebastian-meyer** [comment]
Votes: 21

**Comment by solth** [comment]
:2nd_place_medal:

**Comment by stweil** [comment]
There is still no TYPO3 extension available on TER for TYPO3 12, so an installation fails:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires kitodo/presentation 5.0.6 -> satisfiable by kitodo/presentation[v5.0.6].
    - kitodo/presentation v5.0.6 requires typo3/cms-core ^10.4.37|^11.5.40 -> found typo3/cms-core[v10.4.37, v11.5.40, v11.5.41] but it conflicts with your root composer.json require (^12.4.0).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

I suggest to reopen the issue until a new release with the required updates is provided.

For my further tests I used the latest code from the master branch.

**Comment by stweil** [comment]
"Check TCA Migrations" reports a lengthy list of issues:
```
TCA migrations need to be applied
Check the following list and apply needed changes.
[...]
```

How should these issues be handled?

**Comment by stweil** [comment]
"Scan Extension Files" also reports a very long list with breaking changes and deprecations.

**Comment by thomaslow** [comment]
Hi Stefan,

Thank you for testing the Typo3 v12 update.

> There is still no TYPO3 extension available on TER for TYPO3 12

Yes, the Typo3 v12 support is currently only available in the master branch. I'm sure @sebastian-meyer will prepare a 6.x release soon(ish). In the meantime, I would appreciate any feedback on the Typo3 v12 update (from the current master branch).

> "Scan Extension Files" also reports a very long list

In order to maintain compatibility with Typo3 v11, I tried to fix all deprecation warnings reported by Typo3 v11. Unfortunately, we cannot fix all warnings reported by Typo3 v12 because these changes will likely break compatibility with Typo3 v11.

Also, keep in mind that the Typo3 "extension scanner" is only running a set of regular expressions, which means there are plenty of false positives (e.g. references to internal methods that have the same name as deprecated Typo3 methods, which lead to several false positive deprecation warnings).

> "Check TCA Migrations" reports a lengthy list of issues

I'll have to check those again. There are still 2 warnings even with a fresh Typo3 v11 installation. However, so far they do not seem to cause any trouble, neither with v11 nor v12. I will investigate this next week.
