### ISSUE TITLE
[BUG] Date search results in error

### ISSUE THREAD

**Issue by csidirop** [kitodo/kitodo-presentation#936]
## Description

Trying to use the date search results in an error. 

This input: 
![grafik](https://user-images.githubusercontent.com/43964592/229163625-35a0c193-7780-4e43-b059-f245aaeb2448.png)

leads to this error: 
![grafik](https://user-images.githubusercontent.com/43964592/229163698-f037e289-a3f2-4351-8512-dd4d1cd6f78b.png)

Nothing is written to the log.

## Reproduction

Steps to reproduce the behaviour:

1. Go to your search view page
2. Set the date range
3. Click on search

## Expected Behavior

Filter results. 

## Screenshots and Examples

-

## Environment

 -  OS version: Debian
 -  RDBMS version: Maria DB (MySQL 5.5.5-10.11.2-MariaDB-1:10.11.2+maria~ubu2204 )
 -  Apache Solr version: 8.11.2 ([docker](https://hub.docker.com/_/solr/))
 -  TYPO3 version: 10.4.37-dev
 -  PHP version: 7.4.33

**Comment by michaelkubina** [comment]
Hello Chris,
i am trying to replicate your error, but i cannot encounter this exception. I see, that you are using the extended search, but in my tests it worked as well, so it does not seem to be the issue.

Could you provide me some additional imformation?

- what browser are you using?
- are you using the general schema.xml in your solr instance?
- how does a indexed document look like in your solr? have dates been indexed?
- how does a METS look like for a particular object?

The reason i am asking, is because solr is strict about the format of the date-input:

- if your browser sends a "16000101" instead of "1600-01-01" we would run into an solr-error. If so, then we would need to sanitize the dateformat during query time as well, as it is already implemented for the indexer.
- if the indexer has not been able to get any dates (e.g. wrong XPATH or invalid dateformats), then without the presence of a date-field in any of your indexed documents, we would run into an "undefined fields" error.
- or maybe its something completly different, that i have not thought before

In any case i need some further insight.

With best regards,
Michael

**Comment by csidirop** [comment]
Hi Michael, 
thank you for your reply!

> Could you provide me some additional imformation?

 - **Browser:** Firefox 102.9.0esr (64-Bit) and chromium-based browsers
 - **solr schema:** The one coming with presentation https://github.com/kitodo/kitodo-presentation/tree/4.x/Configuration/ApacheSolr/configsets/dlf/conf
 - **My METS examples:** (I tracked down some possibly faulty mets, but even with only three the date search dont work.)
    - https://digi.bib.uni-mannheim.de/fileadmin/digi/445662204/445662204.xml 
    - https://digi.bib.uni-mannheim.de/fileadmin/digi/1652989919/1652989919.xml
    - https://digi.bib.uni-mannheim.de/fileadmin/digi/1652998276/1652998276.xml
 - Manually indexed via `./vendor/bin/typo3 kitodo:index -d METS-URL -p 3 -s dlf`
 - The year of publications has been indexed: 
![grafik](https://user-images.githubusercontent.com/43964592/232498487-e0ff5d75-2bb6-4f0f-b3c9-012686411b22.png)
and is shown in the side panel: 
![grafik](https://user-images.githubusercontent.com/43964592/232498633-7bed1d60-5129-4da3-a61e-118a959f4647.png)
 But [some](https://digi.bib.uni-mannheim.de/fileadmin/digi/500388547/500388547_anchor.xml) have dates in following format: 
![grafik](https://user-images.githubusercontent.com/43964592/232498973-c9fb0c39-ce1f-46d7-8557-51ccbe9ee0af.png)
or none ([this one](https://digi.bib.uni-mannheim.de/vl/ubmadesb/oai:digi.bib.uni-mannheim.de:51284.xml))

It is still possible that my setup or the config is not correct. You can try out my docker environment: https://github.com/UB-Mannheim/kitodo-presentation-docker/tree/dfg-viewer-6.x-ocr
Just start it with `docker compose --profile with-solr up` (first time will need some time)

**Comment by michaelkubina** [comment]
I have no Docker-Setup yet and would need to set it up on my private desktop (which i will do, if we cant resolve it maybe even earlier), as its a longer process to get it here on my employers machine.

But i took a quick look at your repository and am i assuming right, that your docker actually uses this configuration? https://github.com/UB-Mannheim/kitodo-presentation-docker/tree/dfg-viewer-6.x-ocr/volumes/solr/solrconfig/dlf/conf

Or are you really using the one you mentioned, and i just cant find it in your repository? Are you sideloading it somewhere else...cant find it in the docker-compose.yml https://github.com/kitodo/kitodo-presentation/tree/4.x/Configuration/ApacheSolr/configsets/dlf/conf

Because the one in your repository is different, than the one in the current master branch. In https://github.com/UB-Mannheim/kitodo-presentation-docker/tree/dfg-viewer-6.x-ocr/volumes/solr/solrconfig/dlf/conf your schema.xml is missing the new "daterange" fieldtype and the declaration of the "date"-field, both required for the datesearch.

And also the dynamic field "*_sorting" is still of the type "standard", which causes irratical sorting as it uses an analyzerchain. It should be changed to a "string" fieldtype" instead. (see this issue, which got resolved in a PR https://github.com/kitodo/kitodo-presentation/issues/863)

Years like 17XX or even determined dates like [1812] or [ca. 1850] are not properly ISO or w3cdtf formatted and indexing the datefield will omit those. This is something, that needs some care in some of our METS-Files as well, as it has been imported from our OPAC this way. A full overview of accepted formats for the datefield (in appliance to ISO8601 and extended ISO8601) can be found here: https://github.com/kitodo/kitodo-presentation/pull/869#discussion_r1044412627

Do you mind checking your schema.xml again?

**Comment by csidirop** [comment]
> Because the one in your repository is different, than the one in the current master branch. In https://github.com/UB-Mannheim/kitodo-presentation-docker/tree/dfg-viewer-6.x-ocr/volumes/solr/solrconfig/dlf/conf your schema.xml is missing the new "daterange" fieldtype and the declaration of the "date"-field, both required for the datesearch.

You are right, I was using the outdated v1.6 instead of v1.7. 

The error is now gone, but no results are shown. Just the same search page. Anything still missing?

**Comment by michaelkubina** [comment]
This is promising...great to hear!

Sorry that i have to ask, but have you re-indexed the documents or indexed any new documents afterwards? If not, then the documents in the solr are still indexed according to the old schema.xml and thus are missing the date field in the index itself. Its required to re-index, so the value gets written out to the index.

Sidenote: If you have applied the changes to "*_sorting" as well, then you need to start with a fresh index anyway, because it would result in datatype-mismatch errors.

**Comment by csidirop** [comment]
I'm starting a fresh container and thus have to re-index the documents every time for those tests. 

> Sidenote: If you have applied the changes to "*_sorting" as well

I replaced the whole config folder with the updated one in [presentation v4](https://github.com/kitodo/kitodo-presentation/tree/4.x/Configuration/ApacheSolr/configsets/dlf/conf). Should I have done something else?

**Comment by michaelkubina** [comment]
> I replaced the whole config folder with the updated one in [presentation v4](https://github.com/kitodo/kitodo-presentation/tree/4.x/Configuration/ApacheSolr/configsets/dlf/conf). Should I have done something else?

No, this is fine!

I believe, i understand the issue now...

You will not find the date-field in the Documents of your Document-Repository (in your Typo3-Backend), as there's currently no intended output for it in the `tx_dlf_documents.php` and no Label in the `Labels.xml` - but maybe worth a discussion. 
Its like with the language-field, that has no representation there as well, though it has got its own viewhelper for translation of the ISO-639 encoding, that gets applied on language-facets, metadata and in the listview.
So looking at a document in the Typo3-Backend will always show you a "missing" datefield and also a "missing" language code...even if both get indexed properly.

For the language code to work, it needs the Metadata set up in the Metadata-Repository with the indexname, that gets called in the sourcecode - in this case `language`.

I believe, the issue you have right now, is that the Metadata needs to be set up in your Typo3 backend as well - so you need a field with the index-name `date`...with a custom XPATH or with the build-in Fallback to `MetadataDefaults.php` => `./mods:originInfo/*[@encoding="iso8601" or @encoding="w3cdtf"][@keyDate="yes"]`. Without it, kitodo.presentation wont index it by itself and it will be missing in the solr-index, thus returning no results.

![metadata](https://user-images.githubusercontent.com/3315230/233088257-df3e6861-94e4-4b9b-8af3-ad2cd837dcb8.PNG)

**Comment by csidirop** [comment]
So the `Creation Date` is not the same as `date` ?

But, after adding `date` like you suggested the date search works as expected:
![grafik](https://user-images.githubusercontent.com/43964592/233313117-4622ef49-d86e-4179-a4de-c11809210d2e.png)
![grafik](https://user-images.githubusercontent.com/43964592/233313177-1c2df170-603d-4cb0-bbb3-f86fe0a2e577.png)

Thanks!

Is there any reason why its not a default metadata index? I am not that familiar with the mods specs, but the date should be more or less the same key.

**Comment by sebastian-meyer** [comment]
> Is there any reason why its not a default metadata index? I am not that familiar with the mods specs, but the date should be more or less the same key.

It actually is part of the default metadata configuration: https://github.com/kitodo/kitodo-presentation/blob/master/Resources/Private/Data/MetadataDefaults.php#L83-L101

**Comment by csidirop** [comment]
Oh how could I miss that. I'm still working on the 4.0 branch, which doesn't have my changes (https://github.com/kitodo/kitodo-presentation/commit/4d732a432663f294f31f4e42a36ccddd22d607c5) here yet. 

Some other question not 100% related: In presentation v3.x all metadata an structures were created automatically (or where they with the DFG-Viewer setup?), but in presentation v4 they are not:

TYPO3 v9 & presentation v3.3.4 & DFG-Viewer 5.2:
![grafik](https://user-images.githubusercontent.com/43964592/233580493-bc3a69a5-386d-49b8-9805-ae1d57c6f554.png) 

TYPO3 v10 & presentation v4.0 & DFG-Viewer 6.0:
![grafik](https://user-images.githubusercontent.com/43964592/233580517-c88950a7-3d3d-4caa-bba9-1f676c590312.png)

Is there a reason for this?

**Comment by sebastian-meyer** [comment]
Kitodo.Presentation always required manually importing the default settings for every tenant using the "New Tenant" backend module. That's because we can't guess which sysfolder or pagetree the user wants to have Kitodo.Presentation installed to (or if he/she wants to use the default settings at all). Also, if you have a multi-tenant installation you'll want to import the settings into multiple sysfolders.

The DFG-Viewer on the other hand is meant to be a standalone web service always using the official METS/MODS mappings of the "DFG-Praxisregeln", that's why its installation routine automatically creates all necessary pages and sysfolders, imports the default configuration and sets everything up ready to go.
(It's just a coincidence that many developers use the DFG-Viewer to conveniently set up a Kitodo.Presentation instance for development and testing. That's fine, just be aware that not everything you see is purely Kitodo.Presentation.)

**Comment by csidirop** [comment]
Yes, but what I meant is that `structures` and `metadata` used to be automatically generated and now they are not. 
But - as I now understand -  that is probably a problem with the DFG-Viewer and should be addressed there. Thanks
